version: '3.8'

services:
  resume-extractor:
    build: .
    container_name: resume-extractor
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped